name: Build and push to dockerhub
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  build-and-push:
    name: Build web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: schizo99/sauna-web

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build-and-push
    name: Deploy web
    runs-on: ubuntu-latest
    steps:
      - name: Set up WireGuard Connection
        run: |
          sudo apt-get -y install wireguard resolvconf
          echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf
          sudo chmod 600 wg0.conf
          sudo wg-quick up ./wg0.conf
      - name: Verify connection
        run: ping -c 1 ${{ secrets.SSH_HOST }}
      - name: Setup SSH Agent
        run: |
          mkdir -p ~/.ssh
          echo -n "${{ secrets.SSH_KEY }}" | base64 -d > id_rsa
          chmod 0400 id_rsa
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          -- "cd dc/sauna && docker compose pull && docker compose up -d"
