on:
  push:
    branches:
      - cicd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up WireGuard Connection
        run: |
          #sudo apt install resolvconf
          sudo apt install wireguard
          echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf
          sudo chmod 600 wg0.conf
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 10.0.0.13
          sudo wg setconf wg0 wg0.conf
          sudo ip link set up dev wg0
          ip a
          ip r
          ping -c 4 192.168.101.223